class UpdateOrderForCategory < ActiveRecord::Migration
  def up
    execute <<-SQL
      UPDATE CATEGORIES SET ORDER_NUMBER=1 WHERE NAME='clothes';
      UPDATE CATEGORIES SET ORDER_NUMBER=2 WHERE NAME='books';
      UPDATE CATEGORIES SET ORDER_NUMBER=3 WHERE NAME='electronics';
      UPDATE CATEGORIES SET ORDER_NUMBER=4 WHERE NAME='furniture';
      UPDATE CATEGORIES SET ORDER_NUMBER=5 WHERE NAME='money';
      UPDATE CATEGORIES SET ORDER_NUMBER=6 WHERE NAME='people';
      UPDATE CATEGORIES SET ORDER_NUMBER=7 WHERE NAME='other';
    SQL
  end

  def down

  end
end
